name: ingles_para_criancas
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  audioplayers: ^0.13.5
  flutter_shine: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    #imagens
    #School
    - assets/images/notebook.png

    #Animals
    - assets/images/cao.png
    - assets/images/direitos.png
    - assets/images/gato.png
    - assets/images/leao.png
    - assets/images/macaco.png
    - assets/images/ovelha.png
    - assets/images/segundo_fundo.png
    - assets/images/vaca.png
    #Numbers
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/6.png
    #Toys
    - assets/images/swing.jpeg
    - assets/images/slide.jpeg
    - assets/images/remote_control_car.jpeg
    - assets/images/rattle.png
    - assets/images/helicoptero.png
    - assets/images/peao.png
    - assets/images/boneca.png
    - assets/images/blocks.jpeg
    - assets/images/ball.jpeg
    - assets/images/bowling_ball.jpeg
    - assets/images/robo.png
    - assets/images/yellow_plane.png
    - assets/images/flying_saucer.png
    - assets/images/rocket.png
    - assets/images/menino.png
    - assets/images/casa.png
    - assets/images/shuttlecock.png
    - assets/images/flag_eua.png
    - assets/images/flag_children.jpeg
    - assets/images/little_train.jpeg
    - assets/images/cart.jpeg
    #Aphabet
    - assets/images/A.png
    - assets/images/B.png
    - assets/images/C.png
    - assets/images/D.png
    - assets/images/E.png
    - assets/images/F.png
    - assets/images/G.png
    - assets/images/H.png
    - assets/images/I.png
    - assets/images/J.png
    - assets/images/K.png
    - assets/images/L.png
    - assets/images/M.png
    - assets/images/N.png
    - assets/images/O.png
    - assets/images/P.png
    - assets/images/Q.png
    - assets/images/R.png
    - assets/images/S.png
    - assets/images/T.png
    - assets/images/U.png
    - assets/images/V.png
    - assets/images/W.png
    - assets/images/X.png
    - assets/images/Y.png
    - assets/images/Z.png
    - assets/images/rainbow.png

    #School
    - assets/images/apagador_de_lousa.jpeg
    - assets/images/borracha_escolar.png
    - assets/images/notebook.png
    - assets/images/pen.png
    - assets/images/carteira_escolar.png
    - assets/images/coracao_polka.png
    - assets/images/estojo.jpeg
    - assets/images/giz_de_cera.jpeg
    - assets/images/giz.jpeg
    - assets/images/apagador_de_lousa.jpeg
    - assets/images/apagador_de_lousa.jpeg
    - assets/images/lapis.png
    - assets/images/lousa.png
    - assets/images/mesa.jpeg
    - assets/images/mochila_escolar.png
    - assets/images/uniforme_escolar.jpeg
    - assets/images/uniforme.jpeg
    - assets/images/ursinho_marrom.png
    - assets/images/cooker.jpeg

    #Persons
    - assets/images/baby.png
    - assets/images/boy.png
    - assets/images/boyfriend.jpeg
    - assets/images/brothers.png
    - assets/images/couple.jpeg
    - assets/images/father.png
    - assets/images/girl.jpg
    - assets/images/girlfriend.png
    - assets/images/grandfather.png
    - assets/images/grandmother.png
    - assets/images/mother.png
    - assets/images/pessoas.png
    - assets/images/professions.jpeg
    - assets/images/menina.png
    - assets/images/Pngtree_uncle.png
    - assets/images/Pngtree_aunt.png
    - assets/images/Pngtree_nephew.png
    - assets/images/Pngtree_niece.png
    - assets/images/friends.jpeg
    - assets/images/neighbor.jpeg
    #Vehicles
    - assets/images/ambulance.png
    - assets/images/bike.jpeg
    - assets/images/bulldozer.jpeg
    - assets/images/bus.jpeg
    - assets/images/car.png
    - assets/images/fire_truck.jpeg
    - assets/images/motorcycle.png
    - assets/images/plane.png
    - assets/images/police_car.jpeg
    - assets/images/race_car.jpeg
    - assets/images/racing_bike.jpeg
    - assets/images/ship.jpeg
    - assets/images/tractor.jpeg
    - assets/images/train.jpeg
    - assets/images/truck.jpeg
    - assets/images/garbage_truck.jpeg
    - assets/images/helicopter.png
    - assets/images/tow_truck.png
    #Fruit
    - assets/images/apple.jpeg
    - assets/images/avocado.jpeg
    - assets/images/banana.jpeg
    - assets/images/coconut.jpeg
    - assets/images/grape.jpeg
    - assets/images/kiwi.jpeg
    - assets/images/lemon.jpeg
    - assets/images/mango.jpeg
    - assets/images/melon.jpeg
    - assets/images/orange.jpeg
    - assets/images/peach.jpeg
    - assets/images/pineapple.jpeg
    - assets/images/strawberry.jpeg
    - assets/images/wait.jpeg
    - assets/images/watermelon.jpeg



    #audios
    #School
    - assets/images/notebook.png


    #Fruit
    - assets/audios/watermelon.mp3
    - assets/audios/apple.mp3
    - assets/audios/avocado.mp3
    - assets/audios/banana.mp3
    - assets/audios/coconut.mp3
    - assets/audios/grape.mp3
    - assets/audios/kiwi.mp3
    - assets/audios/lemon.mp3
    - assets/audios/mango.mp3
    - assets/audios/melon.mp3
    - assets/audios/orange.mp3
    - assets/audios/peach.mp3
    - assets/audios/pineapple.mp3
    - assets/audios/strawberry.mp3
    - assets/audios/wait.mp3
    #Vehicles
    - assets/audios/tow_truck.mp3
    - assets/audios/helicopter.mp3
    - assets/audios/garbage_truck.mp3
    - assets/audios/ambulance.mp3
    - assets/audios/bike.mp3
    - assets/audios/bulldozer.mp3
    - assets/audios/bus.mp3
    - assets/audios/car.mp3
    - assets/audios/fire_truck.mp3
    - assets/audios/motorcycle.mp3
    - assets/audios/plane.mp3
    - assets/audios/police_car.mp3
    - assets/audios/race_car.mp3
    - assets/audios/racing_bike.mp3
    - assets/audios/ship.mp3
    - assets/audios/tractor.mp3
    - assets/audios/train.mp3
    - assets/audios/truck.mp3

    #Animals
    - assets/audios/cao.mp3
    - assets/audios/gato.mp3
    - assets/audios/leao.mp3
    - assets/audios/macaco.mp3
    - assets/audios/ovelha.mp3
    - assets/audios/vaca.mp3
    #Numbers
    - assets/audios/zero.mp3
    - assets/audios/1.mp3
    - assets/audios/2.mp3
    - assets/audios/3.mp3
    - assets/audios/4.mp3
    - assets/audios/5.mp3
    - assets/audios/6.mp3
    - assets/audios/7.mp3
    - assets/audios/8.mp3
    - assets/audios/9.mp3
    - assets/audios/10.mp3
    - assets/audios/11.mp3
    - assets/audios/12.mp3
    - assets/audios/13.mp3
    - assets/audios/14.mp3
    - assets/audios/15.mp3
    - assets/audios/16.mp3
    - assets/audios/17.mp3
    - assets/audios/18.mp3
    - assets/audios/19.mp3
    - assets/audios/20.mp3
    - assets/audios/21.mp3
    - assets/audios/22.mp3
    - assets/audios/23.mp3
    #Alphabet
    - assets/audios/a.mp3
    - assets/audios/b.mp3
    - assets/audios/c.mp3
    - assets/audios/d.mp3
    - assets/audios/e.mp3
    - assets/audios/f.mp3
    - assets/audios/g.mp3
    - assets/audios/h.mp3
    - assets/audios/i.mp3
    - assets/audios/j.mp3
    - assets/audios/k.mp3
    - assets/audios/l.mp3
    - assets/audios/m.mp3
    - assets/audios/n.mp3
    - assets/audios/o.mp3
    - assets/audios/p.mp3
    - assets/audios/q.mp3
    - assets/audios/r.mp3
    - assets/audios/s.mp3
    - assets/audios/t.mp3
    - assets/audios/u.mp3
    - assets/audios/v.mp3
    - assets/audios/x.mp3
    - assets/audios/y.mp3
    - assets/audios/w.mp3
    - assets/audios/z.mp3
    - assets/audios/ao.mp3
    #Toys
    - assets/audios/bowling_ball.mp3
    - assets/audios/helicopter.mp3
    - assets/audios/pawn.mp3
    - assets/audios/doll.mp3
    - assets/audios/blocks.mp3
    - assets/audios/ball.mp3
    - assets/audios/robot.mp3
    - assets/audios/toque.mp3
    - assets/audios/home.mp3
    - assets/audios/flying_saucer.mp3
    - assets/audios/shuttlecock.mp3
    - assets/audios/rattle.mp3
    - assets/audios/slide.mp3
    - assets/audios/swing.mp3
    - assets/audios/rocket.mp3
    - assets/audios/little_train.mp3
    - assets/audios/yellow_plane.mp3
    - assets/audios/cart.mp3
    #Colors
    - assets/audios/red.mp3
    - assets/audios/orange.mp3
    - assets/audios/yellow.mp3
    - assets/audios/green.mp3
    - assets/audios/blue.mp3
    - assets/audios/light_blue.mp3
    - assets/audios/brown.mp3
    - assets/audios/black.mp3
    - assets/audios/grey.mp3
    - assets/audios/pink.mp3
    - assets/audios/purple.mp3
    - assets/audios/white.mp3
    #Persons
    - assets/audios/baby.mp3
    - assets/audios/boy.mp3
    - assets/audios/boyfriend.mp3
    - assets/audios/brothers.mp3
    - assets/audios/couple.mp3
    - assets/audios/father.mp3
    - assets/audios/girl.mp3
    - assets/audios/girlfriend.mp3
    - assets/audios/grandfather.mp3
    - assets/audios/grandmother.mp3
    - assets/audios/mother.mp3
    - assets/audios/aunt.mp3
    - assets/audios/uncle.mp3
    - assets/audios/people.mp3
    - assets/audios/professions.mp3
    - assets/audios/nephew.mp3
    - assets/audios/niece.mp3
    - assets/audios/friend.mp3
    - assets/audios/friends.mp3
    - assets/audios/neighbor.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
